name: Node CI

on:
  push:
    branches-ignore:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: List output files
      run: ls build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: mi3-wss6.a2hosting.com
        FTP_USERNAME: mi3-wss6\drogogan
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: ftp
        PORT: 21
        LOCAL_DIR: build
        REMOTE_DIR: "httpdocs/dnd"
        ARGS: --delete --exclude-glob=*.pdf
